import type { Category, Product } from "@/types/ecommerce";

export const MOCK_CATEGORIES: Category[] = [
  {
    id: "cat-mixers-kitchens",
    name_en: "Kitchen Mixers",
    name_ar: "خلاطات مطابخ",
    slug: "mixers-kitchens",
    image_url: "/images/promo/faucet-banner.jpg",
    parent_id: null,
    sort_order: 1,
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-mixers-basins",
    name_en: "Basin Mixers",
    name_ar: "خلاطات أحواض",
    slug: "mixers-basins",
    image_url: "/images/promo/faucet-banner.jpg",
    parent_id: null,
    sort_order: 2,
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-shower-bury",
    name_en: "Shower Systems",
    name_ar: "شاور وأنظمة دش",
    slug: "shower-bury",
    image_url: "/images/promo/shower-banner.jpg",
    parent_id: null,
    sort_order: 3,
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-bathtub-mixers",
    name_en: "Bathtub Mixers",
    name_ar: "خلاطات بانيو",
    slug: "bathtub-mixers",
    image_url: "/images/promo/shower-banner.jpg",
    parent_id: null,
    sort_order: 4,
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-burial-objects",
    name_en: "Concealed Bodies",
    name_ar: "أجسام وخزانات دفن",
    slug: "burial-objects",
    image_url: "/images/promo/shower-banner.jpg",
    parent_id: null,
    sort_order: 5,
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-bathroom-accessories",
    name_en: "Bathroom Accessories",
    name_ar: "إكسسوارات حمام",
    slug: "bathroom-accessories",
    image_url: "/images/promo/faucet-banner.jpg",
    parent_id: null,
    sort_order: 6,
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-faucets",
    name_en: "Faucets & Mixers",
    name_ar: "حنفيات وخلاطات مياه",
    slug: "faucets",
    image_url: "/images/promo/faucet-banner.jpg",
    parent_id: null,
    sort_order: 7,
    created_at: new Date().toISOString(),
  },
  {
    id: "cat-bathtubs",
    name_en: "Freestanding Bathtubs",
    name_ar: "بانيوهات فاخرة",
    slug: "bathtubs",
    image_url: "/images/promo/shower-banner.jpg",
    parent_id: null,
    sort_order: 8,
    created_at: new Date().toISOString(),
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-kitchen-01",
    title_en: "Cassellie Halton Waterfall Mono Basin Mixer Tap",
    title_ar: "خلاط مياه كاسيلي هالتون بشلال انسيابي أحادي الذراع",
    slug: "cassellie-halton-waterfall-mono-basin-mixer-tap",
    sku: "BL-KT-101",
    description_en: "Modern waterfall mono basin & kitchen mixer tap with premium chrome finish and ceramic cartridge.",
    description_ar: "خلاط مطبخ وحوض بتصميم شلال انسيابي حديث مطلي بالكروم اللامع الفاخر مع قلب سيراميكي عالي الدقة.",
    base_price: 97.0,
    discount_price: 85.0,
    category_id: "cat-mixers-kitchens",
    is_concealed: false,
    warranty_years: 10,
    technical_drawing_url: null,
    is_featured: true,
    is_active: true,
    rating: 5,
    brand: "American Standard",
    material: "Brass",
    product_type: "Water Tap",
    in_stock: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[0],
    variants: [
      {
        id: "var-kt-01-chr",
        product_id: "prod-kitchen-01",
        finish_name: "Chrome",
        finish_code: "CHR",
        hex_color: "#D4D4D8",
        image_urls: [],
        stock_quantity: 45,
        price_override: null,
        is_default: true,
        created_at: new Date().toISOString(),
      },
      {
        id: "var-kt-01-gold",
        product_id: "prod-kitchen-01",
        finish_name: "Polished Gold",
        finish_code: "PGD",
        hex_color: "#EAB308",
        image_urls: [],
        stock_quantity: 20,
        price_override: 92.0,
        is_default: false,
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: "prod-kitchen-02",
    title_en: "Parryware Droplet (Quarter Turn Range with Ceramic Innerhead)",
    title_ar: "خلاط باري وير دروبليت بتقنية ربع دورة وقلب سيراميكي",
    slug: "parryware-droplet-quarter-turn-range",
    sku: "BL-KT-102",
    description_en: "Quarter turn kitchen faucet with high-grade ceramic innerhead for effortless control.",
    description_ar: "خلاط مطبخ ربع دورة عالي الجودة مع قلب سيراميكي لتحكم فائق النعومة والدقة في تدفق المياه.",
    base_price: 120.0,
    discount_price: 100.0,
    category_id: "cat-mixers-kitchens",
    is_concealed: false,
    warranty_years: 7,
    technical_drawing_url: null,
    is_featured: true,
    is_active: true,
    rating: 1,
    brand: "Ashirvad Pipes",
    material: "Stainless Steel",
    product_type: "Sanitary",
    in_stock: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[0],
    variants: [
      {
        id: "var-kt-02-chr",
        product_id: "prod-kitchen-02",
        finish_name: "Chrome",
        finish_code: "CHR",
        hex_color: "#D4D4D8",
        image_urls: [],
        stock_quantity: 30,
        price_override: null,
        is_default: true,
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: "prod-kitchen-03",
    title_en: "Booth & Co. Axbridge Lever Mono Kitchen Mixer",
    title_ar: "خلاط مطبخ كلاسيكي بوث آند كو أكسبريدج بذراع تحكم فاخر",
    slug: "booth-co-axbridge-lever-mono-kitchen-mixer",
    sku: "BL-KT-103",
    description_en: "Classic Victorian lever kitchen mixer with dual temperature precision control.",
    description_ar: "خلاط مطبخ كلاسيكي أنيق بذراع تحكم مزدوج بدقة فائقة وجودة نحاسية عالية.",
    base_price: 19.0,
    discount_price: 17.0,
    category_id: "cat-mixers-kitchens",
    is_concealed: false,
    warranty_years: 15,
    technical_drawing_url: null,
    is_featured: true,
    is_active: true,
    rating: 5,
    brand: "GROHE",
    material: "Brass",
    product_type: "Pipes",
    in_stock: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[0],
    variants: [
      {
        id: "var-kt-03-chr",
        product_id: "prod-kitchen-03",
        finish_name: "Chrome",
        finish_code: "CHR",
        hex_color: "#D4D4D8",
        image_urls: [],
        stock_quantity: 50,
        price_override: null,
        is_default: true,
        created_at: new Date().toISOString(),
      },
      {
        id: "var-kt-03-gold",
        product_id: "prod-kitchen-03",
        finish_name: "Polished Gold",
        finish_code: "PGD",
        hex_color: "#EAB308",
        image_urls: [],
        stock_quantity: 25,
        price_override: 22.0,
        is_default: false,
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: "prod-kitchen-04",
    title_en: "Shower Set, Silver Grey Shower Antitwist Hose",
    title_ar: "طقم سماعة دش رمادي فضي مع خرطوم مانع للالتواء",
    slug: "shower-set-silver-grey-antitwist-hose",
    sku: "BL-SHW-104",
    description_en: "High pressure multifunction hand shower set with anti-twist reinforced hose.",
    description_ar: "طقم سماعة دش متعددة الوظائف مع خرطوم مرن ومقاوم للالتواء وضغط تدفق قوي.",
    base_price: 77.0,
    discount_price: 66.0,
    category_id: "cat-mixers-kitchens",
    is_concealed: false,
    warranty_years: 5,
    technical_drawing_url: null,
    is_featured: true,
    is_active: true,
    rating: 5,
    brand: "Kohler",
    material: "Nickel",
    product_type: "Shower",
    in_stock: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[0],
    variants: [
      {
        id: "var-kt-04-nkl",
        product_id: "prod-kitchen-04",
        finish_name: "Brushed Nickel",
        finish_code: "BNK",
        hex_color: "#71717A",
        image_urls: [],
        stock_quantity: 60,
        price_override: null,
        is_default: true,
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: "prod-kitchen-05",
    title_en: "Abode Atlas Monobloc Kitchen Sink Mixer Tap",
    title_ar: "خلاط مطبخ أحادي الكتلة أبود أطلس بقنطرة مرتفعة",
    slug: "abode-atlas-monobloc-kitchen-sink-mixer-tap",
    sku: "BL-KT-105",
    description_en: "Contemporary dual-lever monobloc kitchen faucet engineered for high-durability sink usage.",
    description_ar: "خلاط حوض مطبخ عصري أحادي الكتلة بقنطرة دوارة ومقابض تحكم مزدوجة سلسة.",
    base_price: 25.0,
    discount_price: null,
    category_id: "cat-mixers-kitchens",
    is_concealed: false,
    warranty_years: 10,
    technical_drawing_url: null,
    is_featured: true,
    is_active: true,
    rating: 5,
    brand: "Duravit",
    material: "Stainless Steel",
    product_type: "Water Tap",
    in_stock: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[0],
    variants: [
      {
        id: "var-kt-05-chr",
        product_id: "prod-kitchen-05",
        finish_name: "Chrome",
        finish_code: "CHR",
        hex_color: "#D4D4D8",
        image_urls: [],
        stock_quantity: 40,
        price_override: null,
        is_default: true,
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: "prod-kitchen-06",
    title_en: "Stylish Wholesale Basin Push Tap For Indoors & Outdoors",
    title_ar: "حنفية حوض ضغط أنيقة متعددة الاستخدامات للمنازل والحدائق",
    slug: "stylish-wholesale-basin-push-tap",
    sku: "BL-KT-106",
    description_en: "Automatic shut-off water-saving push button basin tap with solid brass core.",
    description_ar: "حنفية ضغط موفرة للمياه مع إغلاق تلقائي مصنوعة من النحاس الصلب المقاوم للعوامل الجوية.",
    base_price: 44.0,
    discount_price: null,
    category_id: "cat-mixers-kitchens",
    is_concealed: false,
    warranty_years: 8,
    technical_drawing_url: null,
    is_featured: false,
    is_active: true,
    rating: 4,
    brand: "American Standard",
    material: "Bronze",
    product_type: "Sanitary",
    in_stock: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[0],
    variants: [
      {
        id: "var-kt-06-brz",
        product_id: "prod-kitchen-06",
        finish_name: "Warm Sunset",
        finish_code: "WST",
        hex_color: "#B45309",
        image_urls: [],
        stock_quantity: 25,
        price_override: null,
        is_default: true,
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: "prod-kitchen-07",
    title_en: "KOHLER Awaken Halton Waterfall Basin Mixer Tap",
    title_ar: "خلاط حوض ومطبخ كولر أويكن هالتون بتصميم شلال",
    slug: "kohler-awaken-halton-waterfall-basin-mixer-tap",
    sku: "BL-KT-107",
    description_en: "Premium KOHLER waterfall stream mixer with corrosion-resistant finish.",
    description_ar: "خلاط كولر فاخر بتدفق شلالي أنيق ومقاومة تامة للتكلس والصدأ مدى الحياة.",
    base_price: 53.0,
    discount_price: null,
    category_id: "cat-mixers-kitchens",
    is_concealed: false,
    warranty_years: 12,
    technical_drawing_url: null,
    is_featured: true,
    is_active: true,
    rating: 4,
    brand: "Kohler",
    material: "Nickel",
    product_type: "Wash Basins",
    in_stock: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[0],
    variants: [
      {
        id: "var-kt-07-chr",
        product_id: "prod-kitchen-07",
        finish_name: "Chrome",
        finish_code: "CHR",
        hex_color: "#D4D4D8",
        image_urls: [],
        stock_quantity: 35,
        price_override: null,
        is_default: true,
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: "prod-kitchen-08",
    title_en: "Benelave by Hindware Kitchen Sink Tap with Swan Neck",
    title_ar: "خلاط مطبخ بينيلاف برقبة بجعة سوبر سوان نيك",
    slug: "benelave-by-hindware-kitchen-sink-tap-swan-neck",
    sku: "BL-KT-108",
    description_en: "High-arc swivel swan neck kitchen tap with ergonomic handle design.",
    description_ar: "خلاط مطبخ بقوس مرتفع وتصميم رقبة البجعة لسهولة غسيل الأواني الكبيرة وحرية حركة ٣٦٠ درجة.",
    base_price: 35.0,
    discount_price: null,
    category_id: "cat-mixers-kitchens",
    is_concealed: false,
    warranty_years: 5,
    technical_drawing_url: null,
    is_featured: false,
    is_active: true,
    rating: 1,
    brand: "GROHE",
    material: "Brass",
    product_type: "Sanitary",
    in_stock: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[0],
    variants: [
      {
        id: "var-kt-08-chr",
        product_id: "prod-kitchen-08",
        finish_name: "Chrome",
        finish_code: "CHR",
        hex_color: "#D4D4D8",
        image_urls: [],
        stock_quantity: 20,
        price_override: null,
        is_default: true,
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: "prod-kitchen-09",
    title_en: "IKEA Domsjo GLITTRAN Kitchen Faucet Special Additional",
    title_ar: "خلاط مطبخ إيكيا دومسجو جليتران كلاسيكي مع مخرج مياه إضافي",
    slug: "ikea-domsjo-glittran-kitchen-faucet-special-additional",
    sku: "BL-KT-109",
    description_en: "Distinctive classic Nordic bridge kitchen mixer with ceramic detailing.",
    description_ar: "خلاط مطبخ نورديك مميز بتصميم كلاسيكي ومقابض بورسلين بيضاء أنيقة مع تدفق مزدوج.",
    base_price: 79.0,
    discount_price: 72.0,
    category_id: "cat-mixers-kitchens",
    is_concealed: false,
    warranty_years: 10,
    technical_drawing_url: null,
    is_featured: true,
    is_active: true,
    rating: 5,
    brand: "American Standard",
    material: "Nickel",
    product_type: "Pipes",
    in_stock: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[0],
    variants: [
      {
        id: "var-kt-09-mbk",
        product_id: "prod-kitchen-09",
        finish_name: "Matte Black",
        finish_code: "MBK",
        hex_color: "#18181B",
        image_urls: [],
        stock_quantity: 18,
        price_override: null,
        is_default: true,
        created_at: new Date().toISOString(),
      },
      {
        id: "var-kt-09-chr",
        product_id: "prod-kitchen-09",
        finish_name: "Chrome",
        finish_code: "CHR",
        hex_color: "#D4D4D8",
        image_urls: [],
        stock_quantity: 22,
        price_override: 72.0,
        is_default: false,
        created_at: new Date().toISOString(),
      },
    ],
  },
  {
    id: "prod-kitchen-10",
    title_en: "RAK Ceramics Rak Prague One Touch Kitchen Sink Mixer",
    title_ar: "خلاط مطبخ راك سيراميكس براغ بلمسة واحدة وقوس سحب",
    slug: "rak-ceramics-rak-prague-one-touch-kitchen-sink-mixer",
    sku: "BL-KT-110",
    description_en: "Smart one-touch sensor & pull-down spray kitchen mixer with flexible hose.",
    description_ar: "خلاط مطبخ ذكي يعمل باللمس مع خرطوم سحب مرن ورأس رشاش ثنائي الوظائف للتنظيف السريع.",
    base_price: 45.0,
    discount_price: 37.0,
    category_id: "cat-mixers-kitchens",
    is_concealed: false,
    warranty_years: 10,
    technical_drawing_url: null,
    is_featured: true,
    is_active: true,
    rating: 3,
    brand: "Duravit",
    material: "Bronze",
    product_type: "Wash Basins",
    in_stock: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[0],
    variants: [
      {
        id: "var-kt-10-chr",
        product_id: "prod-kitchen-10",
        finish_name: "Chrome",
        finish_code: "CHR",
        hex_color: "#D4D4D8",
        image_urls: [],
        stock_quantity: 30,
        price_override: null,
        is_default: true,
        created_at: new Date().toISOString(),
      },
    ],
  },
];
